### ISSUE TITLE
feat: UI library components

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/cloud-components#103]
## Description

Find and integrate a suitable UI library for building components. Developing a new component library from scratch would be both inefficient and excessive. Therefore, we are seeking a web component library that fulfills the following criteria:
- Web Component Library: The selected library should be based on web components and must not be reliant on third-party libraries such as React or Vue.
- Headless Architecture: It should offer a headless architecture, allowing us to customize the component's UI as per our project's specific needs.

## Possible solution(s)

Some of the potential options available for the library are:
- Fast (https://www.fast.design/docs/components/getting-started/)
- Material Web (https://material-web.dev/)
- Shoelace (https://shoelace.style/)
- Material Tailwind (https://www.material-tailwind.com/)
- Preline (https://preline.co/index.html)
- CSSUI (https://www.cssui.dev/docs/getting-started/introduction/)
- Dracula Theme UI (https://ui.draculatheme.com/)

**Comment by JaeAeich** [comment]
Another possible factor to consider would be the extensiveness of that library in the types of components it offers, working with fast I have realized that:
- Fast doesn't have an exhaustive list of prebuilt components and lacks various useful ones otherwise we'll end up implementing our own.
- Most of the components present barely comply with the guideline set by W3C for that component to be called that component.
  - For Eg: The guideline by W3C for the tooltip is that the component should not be visible on pressing 'Esc' and visible when in focus [etc.](https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/); fast-tooltip complies with that and not other user-specific requirements or UI-specific requirements. Making the component useless as that much we can implement.

**Comment by git-anurag-hub** [comment]
Absolutely, @JaeAeich, your point is well taken. 

Well, I find Shoelace to be the more fitting library for various reasons. Notably, it offers robust design token support, making customization of components effortless. Furthermore, being an open-source web component library, it boasts an extensive and diverse selection of components to cater to various needs.

As for Fast (as it can be the obvious choice), it falls short in comparison due to its limited component offerings, lack of ongoing development, and inferior design customization and accessibility options.

**Comment by git-anurag-hub** [comment]
What do you think about this, @uniqueg and @SalihuDickson ?

**Comment by SalihuDickson** [comment]
> What do you think about this, @uniqueg and @SalihuDickson ?

well, I haven't looked into the library but if you think it suits our needs then I'm inclined to agree, but perhaps you can go a little bit more into the customization options that make it more fitting in our next meeting, as i don't have any experience with the library.

**Comment by uniqueg** [comment]
Agreeing with @JaeAeich and @SalihuDickson. Basically, pick with what best aligns with common standards, conventions and practices and what means the least work for us.

Just don't use any library/dependency that is deprecated or shows signs of decreasing support by the community.
