### ISSUE TITLE
feat(ecc-utils-design): add components

### ISSUE THREAD

**Issue by anuragxxd** [elixir-cloud-aai/cloud-components#114]
## Description

Update the `ecc-utils-design` package by adding new components that will improve the overall usability and design consistency across various ECC packages. These components will be created using the base components from the Shoelace library and will be using design tokens as CSS properties to ensure a consistent and cohesive design language.

Components to be Added:
- [x] #141
- [x] #166
- [ ] Service Info

**Comment by git-anurag-hub** [comment]
Hey @ltwmori & @JaeAeich, Can you guys please decide on what components can be developed first as needed per your projects? Form elements are the one such I can think of as told by @JaeAeich earlier!

**Comment by JaeAeich** [comment]
I would say the hierarchy should be somewhat as follows: 
- inputs
- labels
- accordion
- buttons
- switch
- tabs
- tooltips

>PS: This is based on the general trend I have seen in both mine and @ltwmori's package :+1:

**Comment by JaeAeich** [comment]
@git-anurag-hub should I take any of these because you are assigned to input?

**Comment by git-anurag-hub** [comment]
Since `form` component is almost complete other than methods as mentioned here #157. Let's take other components for the development. @JaeAeich can you please put down what components will you need in the TES & WES here?

**Comment by JaeAeich** [comment]
After the create component, we will need to create runs component for browing tasks and workflows. An `Accordion` is what both of the component will need. Functionality we can expect from the said accordion would be:
- Certain field for basic information like `Run Id`, `status` and aditionally, one or two buttons for easy implementation of `delete runs` feature or `update run` feature. 
- `Pagination`, knowing there isn't a set standard for pagination yet but luckily both TES and WES have a similar schema where where we have a next page cursor which can be used to fetch the later runs.
- The uncollapsed view should contain rendering of object, I believe `recursively due to lack of structure`.
- Uncollapsed view should maybe have an specific `footer we could leverage to show meta` data like date of creation etc. 
- Optionally we could also have `select feature` for them where in if the user want to bulk deletion, it can be performed.

We would also like to be able to edit task from the `runs` component itself so we would also require the form component.

**Comment by SalihuDickson** [comment]
Hey @git-anurag-hub, have you started working on this component that @JaeAeich just described or can I take it up?

**Comment by git-anurag-hub** [comment]
Sure @SalihuDickson
