### ISSUE TITLE
fix: vercel build fails 

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#240]
## Description

`Vercel` fails in `CI` quite often, without any logical error in the code. One of the reason if that `turbo.json` is not specified correctly. The build of different package depend on other packages, but sometimes when pushing creating the PR, if not dependencies aren;t cached npm trip and isn't able to produce a build which breaks preview.

## Possible solution(s)

Look into [this](https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies).

## Additional context

Current build pipeline
![graph](https://github.com/elixir-cloud-aai/cloud-components/assets/100477031/14cfb718-d3a4-45f9-8e32-3b5754fcfb75)
There might be other reasons of `vercel's` fails that this issue hasn't accounted for.

**Comment by uniqueg** [comment]
Noting that this seems to be happening in https://github.com/elixir-cloud-aai/landing-page as well

**Comment by git-anurag-hub** [comment]
> Noting that this seems to be happening in https://github.com/elixir-cloud-aai/landing-page as well

The issue with the landing-page was not directly related to the problem here. The deployments were failing because the pull requests (PRs) were made by first-time contributors. Vercel requires authorization from new users before deploying their changes to prevent spam or malicious deployments. 

However, the reason for the deployment failures here still remains unverified. Have to check again!

**Comment by JaeAeich** [comment]
closing the issue!!
