### ISSUE TITLE
feat: design changes in form component 

### ISSUE THREAD

**Issue by anantJjain** [elixir-cloud-aai/cloud-components#249]
## Description

- Currently "Details" section under the "Address" field has a blue background color making it visually discomfortable to look at.
- The position of "bin" icon is on the left side of the section and don't clearly convey its usage clearly. 

## Possible solution(s)

- Changing the color from blue to a suitable lighter color as per the exisitng color scheme
- Moving the bin icon to the top of each section giving user a clear idea of its functionality
 
## Additional context

Current look : 
![image](https://github.com/elixir-cloud-aai/cloud-components/assets/75206987/9d60502f-849a-4a6e-9478-fae538c731ab)

**Comment by JaeAeich** [comment]
@anantJjain this is not an error or unexpected behaviour, this is just to showcase the extent and ease of the styling configuration of design package. If there is anything to change here, maybe that would be to give better example of the styles using the css parts instead of just changing the bg color and button position. 

BTW both of those are configurable in the design package if Im not wrong.
